package lierengu.settings.mapper;

import lierengu.settings.domain.Admin;

import java.util.Map;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    Admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    int updateByPrimaryKey(Admin record);

    /**
     * 根据账号和密码查询管理员
     * @param map
     * @return
     */
    Admin selectAdminByAdminNameAndPassword(Map<String,Object> map);
}