package lierengu.settings.domain;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.id
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.admin_name
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.password
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.id
     *
     * @return the value of t_administrator.id
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.id
     *
     * @param id the value for t_administrator.id
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.admin_name
     *
     * @return the value of t_administrator.admin_name
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.admin_name
     *
     * @param adminName the value for t_administrator.admin_name
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.password
     *
     * @return the value of t_administrator.password
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.password
     *
     * @param password the value for t_administrator.password
     *
     * @mbggenerated Mon Aug 01 10:06:04 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}